/** Generated Assertion Class - DO NOT CHANGE */
package au.org.greekwelfaresa.idempiere.test.assertj.m_movementlinema;

import au.org.greekwelfaresa.idempiere.test.assertj.po.AbstractPOAssert;
import java.util.Objects;
import javax.annotation.Generated;
import org.compiere.model.X_M_MovementLineMA;

/** Generated assertion class for M_MovementLineMA
 *  @author idempiere-test (generated) 
 *  @version Release 6.2 - $Id$ */
@Generated("class au.org.greekwelfaresa.idempiere.test.generator.ModelAssertionGenerator")
public abstract class AbstractM_MovementLineMAAssert<SELF extends AbstractM_MovementLineMAAssert<SELF, ACTUAL>, ACTUAL extends X_M_MovementLineMA>
	extends AbstractPOAssert<SELF, ACTUAL>
{

    /** Standard Constructor */
    public AbstractM_MovementLineMAAssert (ACTUAL actual, Class<SELF> selfType)
    {
      super (actual, selfType);
    }


	public SELF hasDateMaterialPolicy(Object expected)
	{
		isNotNull();
		dateAssert("DateMaterialPolicy", actual.getDateMaterialPolicy(), expected);
		return myself;
	}


	public SELF isAutoGenerated()
	{
		isNotNull();
		if (!actual.isAutoGenerated()) {
			failWithMessage("\nExpecting PO:\n  <%s>\nto be AutoGenerated\nbut it was not",
				getPODescription());
		}
		return myself;
	}

	public SELF isNotAutoGenerated()
	{
		isNotNull();
		if (actual.isAutoGenerated()) {
			failWithMessage("\nExpecting PO: \n  <%s>\n to not be AutoGenerated\nbut it was",
				getPODescription());
		}
		return myself;
	}

	public SELF hasM_AttributeSetInstance_ID(int expected)
	{
		isNotNull();
		int actualField = actual.getM_AttributeSetInstance_ID();
		if (expected != actualField) {
			failWithActualExpectedAndMessage(actualField, expected, "\nExpecting PO: \n  <%s>\n to have M_AttributeSetInstance_ID: <%s>\nbut it was: <%s>",
				getPODescription(), expected, actualField);
		}
		return myself;
	}

	public SELF hasM_MovementLine_ID(int expected)
	{
		isNotNull();
		int actualField = actual.getM_MovementLine_ID();
		if (expected != actualField) {
			failWithActualExpectedAndMessage(actualField, expected, "\nExpecting PO: \n  <%s>\n to have M_MovementLine_ID: <%s>\nbut it was: <%s>",
				getPODescription(), expected, actualField);
		}
		return myself;
	}

	public SELF hasM_MovementLineMA_UU(String expected)
	{
		isNotNull();
		String actualField = actual.getM_MovementLineMA_UU();
		if (!Objects.equals(expected, actualField)) {
			failWithActualExpectedAndMessage(actualField, expected, "\nExpecting PO: \n  <%s>\n to have M_MovementLineMA_UU: <%s>\nbut it was: <%s>",
				getPODescription(), expected, actualField);
		}
		return myself;
	}

	public SELF hasMovementQty(Object expected)
	{
		isNotNull();
		bdAssert("MovementQty", actual.getMovementQty(), expected);
		return myself;
	}

}